name: run-and-benchmark.yml

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "Cargo.toml"
      - ".github/workflows/run-and-benchmark.yml"

jobs:
  build-and-run:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout 1brc repo"
        uses: actions/checkout@v4
        with:
          repository: gunnarmorling/1brc
          path: './gen-1brc'

      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: "Generate 100 mil rows"
        working-directory: ./gen-1brc
        run: |
          ./mvnw -q clean verify
          ./create_measurements.sh 100000000

      - name: "Checkout this repo"
        uses: actions/checkout@v4
        with:
          path: './1brc'

      - name: "Install rust toolchain"
        uses: dtolnay/rust-toolchain@stable

      - name: "Cargo run"
        working-directory: ./1brc
        run: cargo run --release

      - name: "Upload output.txt"
        uses: actions/upload-artifact@v4
        with:
          name: output.txt
          path: ./1brc/output.txt