name: run-and-benchmark.yml
run-name: ""
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "Cargo.toml"

jobs:
  build-and-run:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build